export const ERROR_CODES = Object.freeze({
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN", AUTH_INVALID_SCHEME: "AUTH_INVALID_SCHEME",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN", AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  PROFILE_MISSING: "PROFILE_MISSING", PROFILE_DUPLICATE_UID: "PROFILE_DUPLICATE_UID",
  PROFILE_DUPLICATE_EMAIL: "PROFILE_DUPLICATE_EMAIL", ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED", ACCOUNT_PENDING: "ACCOUNT_PENDING",
  ACCOUNT_INVITED: "ACCOUNT_INVITED", ROLE_FORBIDDEN: "ROLE_FORBIDDEN", ROLE_UNKNOWN: "ROLE_UNKNOWN",
  VALIDATION_FAILED: "VALIDATION_FAILED", RATE_LIMITED: "RATE_LIMITED", NOT_FOUND: "NOT_FOUND",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE", INTERNAL_ERROR: "INTERNAL_ERROR",
  PROPERTY_UNAVAILABLE: "PROPERTY_UNAVAILABLE", BOOKING_PAST_DATE: "BOOKING_PAST_DATE",
  BOOKING_CONFLICT: "BOOKING_CONFLICT", BOOKING_NOT_CANCELLABLE: "BOOKING_NOT_CANCELLABLE",
  BOOKING_CUTOFF: "BOOKING_CUTOFF", CONVERSATION_FORBIDDEN: "CONVERSATION_FORBIDDEN"
});
