import { beforeEach, describe, expect, it, vi } from "vitest";
import request from "supertest";
import { createApp } from "../../src/app.js";
import ApiError from "../../src/utils/ApiError.js";

const user = { _id: "507f1f77bcf86cd799439011", firebaseUid: "firebase-client", fullName: "Ada Client", email: "ada@example.com", phone: "+2348012345678", role: "client", status: "active", mustChangePassword: false, emailVerified: true, toObject() { const { toObject, ...value } = this; return value; } };
const config = { NODE_ENV: "test", PORT: 3001, MONGODB_URI: "mongodb://mock", CLIENT_ORIGINS: ["http://localhost:8081"], FIREBASE_PROJECT_ID: "test", FIREBASE_CLIENT_EMAIL: "test@example.com", FIREBASE_PRIVATE_KEY: "mock", LOG_LEVEL: "silent" };
const id = "507f1f77bcf86cd799439012";
const bearer = { Authorization: "Bearer valid" };

function fixture(overrides = {}) {
  const propertyService = { list: vi.fn(async () => ({ items: [], pagination: { page: 1 } })), getById: vi.fn(async () => ({ id })), featured: vi.fn(async () => []), recent: vi.fn(async () => []), similar: vi.fn(async () => []), ...overrides.propertyService };
  const favouriteService = { list: vi.fn(async () => ({ items: [], pagination: {} })), add: vi.fn(async () => ({ id })), remove: vi.fn(async () => {}), ids: vi.fn(async () => []), ...overrides.favouriteService };
  const bookingService = { list: vi.fn(async () => ({ items: [], pagination: {} })), create: vi.fn(async () => ({ id })), cancel: vi.fn(async () => ({ id })), ...overrides.bookingService };
  const conversationService = { list: vi.fn(async () => ({ items: [], pagination: {} })), createForProperty: vi.fn(async () => ({ id })), messages: vi.fn(async () => ({ items: [], pagination: {} })), send: vi.fn(async () => ({ id })), markRead: vi.fn(async () => {}), unreadCount: vi.fn(async () => 0), ...overrides.conversationService };
  const notificationService = { list: vi.fn(async () => ({ items: [], pagination: {} })), unreadCount: vi.fn(async () => 0), markRead: vi.fn(async () => ({ id })), markAllRead: vi.fn(async () => {}), remove: vi.fn(async () => {}), ...overrides.notificationService };
  const clientHomeService = { get: vi.fn(async () => ({ featuredProperties: [] })), ...overrides.clientHomeService };
  const userService = { findByFirebaseUid: vi.fn(async () => overrides.user || user), touchLogin: vi.fn(async () => {}), updateOwnProfile: vi.fn(async (doc, updates) => Object.assign(doc, updates)), ...overrides.userService };
  const app = createApp({ config, adminAuth: { verifyIdToken: vi.fn(async () => ({ uid: "firebase-client", email: "ada@example.com", email_verified: true })) }, userService, auditService: { record: vi.fn(async () => {}) }, propertyService, favouriteService, bookingService, conversationService, notificationService, clientHomeService });
  return { app, propertyService, favouriteService, bookingService, conversationService, notificationService, clientHomeService };
}

describe("Phase C client API contracts", () => {
  beforeEach(() => vi.clearAllMocks());
  it("returns a paginated property list", async () => { const f = fixture(); const res = await request(f.app).get("/api/v1/properties?page=2&limit=10&sort=price_low_to_high").set(bearer); expect(res.status).toBe(200); expect(f.propertyService.list).toHaveBeenCalledWith(expect.objectContaining({ page: 2, limit: 10, sort: "price_low_to_high" })); });
  it("rejects excessive page sizes and invalid price ranges", async () => { let res = await request(fixture().app).get("/api/v1/properties?limit=500").set(bearer); expect(res.body.code).toBe("VALIDATION_FAILED"); res = await request(fixture().app).get("/api/v1/properties?minPrice=20&maxPrice=10").set(bearer); expect(res.status).toBe(400); });
  it("rejects invalid property identifiers", async () => { const res = await request(fixture().app).get("/api/v1/properties/not-an-id").set(bearer); expect(res.status).toBe(400); });
  it("gets property detail and similar items", async () => { const f = fixture(); expect((await request(f.app).get(`/api/v1/properties/${id}`).set(bearer)).status).toBe(200); expect((await request(f.app).get(`/api/v1/properties/${id}/similar`).set(bearer)).status).toBe(200); });
  it("derives favourite ownership from the authenticated profile", async () => { const f = fixture(); const res = await request(f.app).post(`/api/v1/favourites/${id}`).set(bearer).send({}); expect(res.status).toBe(201); expect(f.favouriteService.add).toHaveBeenCalledWith(user._id, id); });
  it("rejects favourite owner injection", async () => { const res = await request(fixture().app).post(`/api/v1/favourites/${id}`).set(bearer).send({ userId: "attacker" }); expect(res.status).toBe(400); });
  it("lists and removes only the caller's favourites", async () => { const f = fixture(); await request(f.app).get("/api/v1/favourites").set(bearer); await request(f.app).delete(`/api/v1/favourites/${id}`).set(bearer); expect(f.favouriteService.list).toHaveBeenCalledWith(user._id, expect.any(Object)); expect(f.favouriteService.remove).toHaveBeenCalledWith(user._id, id); });
  it("creates a booking without accepting client or realtor identity", async () => { const f = fixture(); const body = { propertyId: id, scheduledAt: "2027-08-01T10:00:00+01:00", timezone: "Africa/Lagos", message: "Morning please" }; const res = await request(f.app).post("/api/v1/bookings").set(bearer).send(body); expect(res.status).toBe(201); expect(f.bookingService.create).toHaveBeenCalledWith(user._id, expect.objectContaining({ propertyId: id })); const injected = await request(f.app).post("/api/v1/bookings").set(bearer).send({ ...body, clientId: "attacker", realtorId: "attacker" }); expect(injected.status).toBe(400); });
  it("normalizes booking conflicts", async () => { const f = fixture({ bookingService: { create: vi.fn(async () => { throw new ApiError(409, "BOOKING_CONFLICT", "Conflict"); }) } }); const res = await request(f.app).post("/api/v1/bookings").set(bearer).send({ propertyId: id, scheduledAt: "2027-08-01T10:00:00+01:00" }); expect(res.status).toBe(409); expect(res.body.code).toBe("BOOKING_CONFLICT"); });
  it("lists and cancels only the caller's bookings", async () => { const f = fixture(); await request(f.app).get("/api/v1/bookings").set(bearer); await request(f.app).patch(`/api/v1/bookings/${id}/cancel`).set(bearer).send({ reason: "Changed plans" }); expect(f.bookingService.cancel).toHaveBeenCalledWith(user._id, id, "Changed plans"); });
  it("creates property conversations without participant injection", async () => { const f = fixture(); const res = await request(f.app).post("/api/v1/conversations").set(bearer).send({ propertyId: id }); expect(res.status).toBe(201); expect(f.conversationService.createForProperty).toHaveBeenCalledWith(user._id, id); const injected = await request(f.app).post("/api/v1/conversations").set(bearer).send({ propertyId: id, participantIds: ["attacker"] }); expect(injected.status).toBe(400); });
  it("rejects empty messages and sends valid messages as the caller", async () => { let f = fixture(); let res = await request(f.app).post(`/api/v1/conversations/${id}/messages`).set(bearer).send({ text: " " }); expect(res.status).toBe(400); f = fixture(); res = await request(f.app).post(`/api/v1/conversations/${id}/messages`).set(bearer).send({ text: "Hello" }); expect(res.status).toBe(201); expect(f.conversationService.send).toHaveBeenCalledWith(user._id, id, "Hello"); });
  it("marks conversation read through membership-aware service", async () => { const f = fixture(); await request(f.app).patch(`/api/v1/conversations/${id}/read`).set(bearer).send({}); expect(f.conversationService.markRead).toHaveBeenCalledWith(user._id, id); });
  it("scopes notification reads and deletes to the caller", async () => { const f = fixture(); await request(f.app).patch(`/api/v1/notifications/${id}/read`).set(bearer).send({}); await request(f.app).delete(`/api/v1/notifications/${id}`).set(bearer).send({}); expect(f.notificationService.markRead).toHaveBeenCalledWith(user._id, id); expect(f.notificationService.remove).toHaveBeenCalledWith(user._id, id); });
  it("rejects profile role, status, and Firebase UID injection", async () => { for (const field of ["role", "status", "firebaseUid"]) { const res = await request(fixture().app).patch("/api/v1/profile").set(bearer).send({ [field]: "admin" }); expect(res.status).toBe(400); } });
  it("blocks non-client MongoDB roles", async () => { const res = await request(fixture({ user: { ...user, role: "realtor" } }).app).get("/api/v1/properties").set(bearer); expect(res.status).toBe(403); expect(res.body.code).toBe("ROLE_FORBIDDEN"); });
  it("loads the compact Client Home aggregate", async () => { const f = fixture(); const res = await request(f.app).get("/api/v1/client/home").set(bearer); expect(res.status).toBe(200); expect(f.clientHomeService.get).toHaveBeenCalledWith(user); });
});
