import ApiError from "../utils/ApiError.js";
import { ERROR_CODES } from "../constants/errorCodes.js";
import { CLIENT_VISIBLE_PROPERTY_STATUSES } from "../constants/propertyStatuses.js";
import { paginationMeta } from "../utils/pagination.js";
import { propertyResponse } from "../utils/clientSerializers.js";

const sortMap = { newest: { publishedAt: -1, _id: -1 }, price_low_to_high: { price: 1, _id: 1 }, price_high_to_low: { price: -1, _id: -1 } };
function buildFilter(query) { const filter = { status: { $in: CLIENT_VISIBLE_PROPERTY_STATUSES } }; if (query.search) filter.$text = { $search: query.search }; if (query.propertyType) filter.propertyType = query.propertyType; if (query.listingType) filter.listingType = query.listingType; if (query.city) filter.city = new RegExp(`^${query.city.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "i"); if (query.state) filter.state = new RegExp(`^${query.state.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "i"); if (query.country) filter.country = new RegExp(`^${query.country.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "i"); if (query.minPrice != null || query.maxPrice != null) filter.price = { ...(query.minPrice != null ? { $gte: query.minPrice } : {}), ...(query.maxPrice != null ? { $lte: query.maxPrice } : {}) }; if (query.minBedrooms != null) filter.bedrooms = { $gte: query.minBedrooms }; if (query.minBathrooms != null) filter.bathrooms = { $gte: query.minBathrooms }; if (query.featured != null) filter.featured = query.featured; return filter; }
export function createPropertyService(PropertyModel) { return {
  async list(query) { const filter = buildFilter(query); const skip = (query.page - 1) * query.limit; const sort = query.sort === "most_relevant" && query.search ? { score: { $meta: "textScore" } } : sortMap[query.sort] || sortMap.newest; const [items, totalItems] = await Promise.all([PropertyModel.find(filter).populate("realtorId", "fullName avatar").sort(sort).skip(skip).limit(query.limit).lean(), PropertyModel.countDocuments(filter)]); return { items: items.map(propertyResponse), pagination: paginationMeta(query.page, query.limit, totalItems) }; },
  async getById(propertyId) { const item = await PropertyModel.findOne({ _id: propertyId, status: { $in: CLIENT_VISIBLE_PROPERTY_STATUSES } }).populate("realtorId", "fullName avatar").lean(); if (!item) throw new ApiError(404, ERROR_CODES.NOT_FOUND, "This property is unavailable."); return propertyResponse(item); },
  async featured(limit = 6) { const items = await PropertyModel.find({ status: "active", featured: true }).populate("realtorId", "fullName avatar").sort({ publishedAt: -1 }).limit(limit).lean(); return items.map(propertyResponse); },
  async recent(limit = 8) { const items = await PropertyModel.find({ status: "active" }).populate("realtorId", "fullName avatar").sort({ publishedAt: -1 }).limit(limit).lean(); return items.map(propertyResponse); },
  async similar(propertyId, limit = 4) { const source = await PropertyModel.findOne({ _id: propertyId, status: { $in: CLIENT_VISIBLE_PROPERTY_STATUSES } }).lean(); if (!source) throw new ApiError(404, ERROR_CODES.NOT_FOUND, "This property is unavailable."); const items = await PropertyModel.find({ _id: { $ne: source._id }, status: "active", $or: [{ city: source.city }, { propertyType: source.propertyType }, { listingType: source.listingType }] }).populate("realtorId", "fullName avatar").sort({ featured: -1, publishedAt: -1 }).limit(limit).lean(); return items.map(propertyResponse); }
}; }
